name: Calens Changelog

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  changelog:
    uses: owncloud/reusable-workflows/.github/workflows/calens.yml@main
    secrets:
      TRANSLATION_APP_ID: ${{ secrets.TRANSLATION_APP_ID }}
      TRANSLATION_APP_PRIVATE_KEY: ${{ secrets.TRANSLATION_APP_PRIVATE_KEY }}
