name: Conventional Commits

on:
  pull_request:
    # Just some events that could involve commit messages
    types: [opened, synchronize, reopened]

permissions:
  # Only need read access to repository contents
  contents: read

jobs:
  validate-commit-names:
    uses: owncloud/reusable-workflows/.github/workflows/semantic-git-message.yml@main
