name: "Update translations"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  update-translations:
    uses: owncloud/reusable-workflows/.github/workflows/translation-sync.yml@main
    with:
      mode: native
      sub_path: .
    secrets:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}
      TRANSLATION_APP_ID: ${{ secrets.TRANSLATION_APP_ID }}
      TRANSLATION_APP_PRIVATE_KEY: ${{ secrets.TRANSLATION_APP_PRIVATE_KEY }}
