name: Validate Android source strings

on:
  push:

permissions:
  contents: read

jobs:
  validate-strings:
    name: Validate strings
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Install xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet

      - name: Validate source strings
        shell: bash
        run: |
          xml_file="owncloudApp/src/main/res/values/strings.xml"
          has_errors=0

          # ANSI-C quoting to read characters correctly
          forbidden_values=($'\'' $'"' $'@' $'\n' $'\t')
          escaped_values=($'\\\'' $'\\"' $'\\@' $'\\n' $'\\t')

          # Read one line every iteration
          while IFS= read -r line; do

            # Takes everything on the left of ^^
            string_name="${line%%^^*}"
            # Takes everything on the right of ^^
            string_value="${line#*^^}"

            # Check if the string contains any of the escaped_values and remove it
            for escaped in "${escaped_values[@]}"; do
              string_value="${string_value//"$escaped"/}"
            done

            # Check if the string contains any of the forbidden_values
            for forbidden in "${forbidden_values[@]}"; do
              if [[ "$string_value" == *"$forbidden"* ]]; then
                echo "Source string \"$string_name\" contains forbidden characters"
                has_errors=1
                break
              fi
            done
          # Read the input file line by line
          done < <(
            xmlstarlet sel \
              -t \
              -m '/resources/string' \
              -v '@name' \
              -o '^^' \
              -v '.' \
              -n \
              "$xml_file"
          )

          exit $has_errors
